In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
fname_unaligned = "../experiments/datasets/RR/PF00072_unaligned.csv"
fname_aligned = "../experiments/datasets/RR/RR.csv"

df_aligned = pd.read_csv(fname_aligned)
df_unaligned = pd.read_csv(fname_unaligned)

print("Aligned data shape:", df_aligned.shape)
print("Unaligned data shape:", df_unaligned.shape)

Aligned data shape: (855395, 3)
Unaligned data shape: (897631, 3)

In [6]:
df_unaligned.head()

,header,sequence,label
0,tr|A0A519QNX6|A0A519QNX6_9CAUL/2-78 >tr|A0A519...,AANGQAAVAETARLRPDVVVLDLEMPVMDGMTALPLILAAHPGVKV...,PF01339
1,tr|A0A497E6X2|A0A497E6X2_UNCAI/1-78 >tr|A0A497...,AANGRIALAKIPRLNPDLVTLDVEMPEMDGLETLSRIRADFPSIKV...,PF01339
2,tr|A0A2U3LPI8|A0A2U3LPI8_9BACT/2-101 >tr|A0A2U...,ADDSALMRQTLKRIVDAEPGLELAGLARDGEDAVAKARELKPDVVT...,PF01339
3,tr|A0A1W7QQA6|A0A1W7QQA6_9BACT/2-103 >tr|A0A1W...,ADDSALVRQILRDILQEEEDIELAGEACDGRQACELTFRLRPDLVI...,PF01339
4,tr|A0A089P0W8|A0A089P0W8_9HYPH/2-104 >tr|A0A08...,ADDSAVVRGLVARWIGEAGFELVGTASNGRIALELMAKHDPDVVLL...,PF01339

In [7]:
# extract sequence identifiers from the 'header' column in the unaligned dataframe
def get_id(header):
    return header.split("|")[1]

df_unaligned.rename(columns={"header": "full_header"}, inplace=True)
df_unaligned["header"] = df_unaligned["full_header"].apply(get_id)

In [8]:
# join the two dataframes on the 'header' column. Change the 'sequence' column of the aligned dataframe to 'sequence_align' to avoid confusion. Discard rows with no match in the unaligned dataframe.
df_merged = pd.merge(df_aligned.rename(columns={"sequence": "sequence_align"}), df_unaligned, on="header", how="inner")
print("Merged data shape:", df_merged.shape)

Merged data shape: (869100, 6)

In [15]:
df_merge = df_aligned.rename(columns={"sequence": "sequence_align"}).merge(df_unaligned, on=["header", "label"], how="inner").filter(items=['header', 'sequence_align', 'sequence', 'label'])
print("Merged data shape:", df_merge.shape)
df_merge.head()

Merged data shape: (855395, 4)

,header,sequence_align,sequence,label
0,A0A4R2LXV1,----------------------AEITLTAGAEQAIQQLQSGAVDLF...,TGDILRSGLGAEAEITLTAGAEQAIQQLQSGAVDLFIADVERFDVA...,PF12833
1,A0A1X7C471,----------------------AKIKQAGNLEEVWALLNRWQVAML...,PGAKIKQAGNLEEVWALLNRWQPVAMLFIEVYLPGLCSLKELAKLC...,PF00196
2,A0A2P8FLB5,----------------------AVVDTASNFREAAHAVSSTHYQLV...,SDAVVDTASNFREAAHAVSSTHYQLVILDLNIPGTDHLLTIEKLRA...,PF00196
3,A0A932B8R2,----------------------CTVMEAGSAEEGAELLRGNHVDLI...,NFLVKTLAPRCQTVMEAGSAEEGAELLRGNHVDLIILDIALPGMNG...,PF00158
4,A0A6N0BT70,----------------------CTVMEAGSAEEGAELLRGNHVDLI...,NFLVKTLAPRCQTVMEAGSAEEGAELLRGNHVDLIILDIALPGRNG...,PF00158

In [16]:
# shuffle and save
df_merge = df_merge.sample(frac=1, random_state=42).reset_index(drop=True)
df_merge.to_csv("../experiments/datasets/RR/RR_merged.csv", index=False)